### PR TITLE
Deploy test configuration (insecure) for librvi

### PR DESCRIPTION
**Pull request by tjamison**
Signed-off-by: Tatiana Jamison <tjamison@jaguarlandrover.com>

### CODE REVIEW

**Comment by tjamison** [comment]
@rstreif This change is being used by the smart-cities build process, would you please review?

**Comment by rstreif** [comment]
Looks good to me. I am just wondering what the reason is for locking libjwt to a specific commit and if that commit matches a release tag of libjwt.

**Comment by tjamison** [comment]
The recipe was previously autorev'd. The maintainer of libjwt made a series of commits on May 23 that caused some otherwise-valid JWTs to fail verification, so I rolled back to the latest known-good commit. I'll modify to the corresponding release commit sha and update the PV accordingly -- will do some further testing with libJWT release 1.8.0

**Comment by rstreif** [comment]
Ok, great thanks for the info.

**Comment by tjamison** [comment]
Closing this -- will make atomic pull requests for (a) versioning and (b) configuration files

**Pull request closed without merging**
